### ISSUE TITLE
Generic email

### ISSUE THREAD

**Issue by anotherjames** [computerminds/cm_tools#16]
hook_email() is daft. Let's make a generic email template, where the parameters passed into it entirely define the subject, content, etc, so that modules don't need to 'define' their emails, but can just call something like this on the fly: 

<?php
drupal_mail('cm_tools', 'generic', $to, $lang, array('subject' => $subject, 'body' => $body));
?>

To be honest, I wonder if this would be better actually being released as a standalone minimodule in contribland, because I bet a lot of other developers would appreciate this!

**Comment by stevetweeddale** [comment]
We could totes just wrap the function, so I can just call:

``` php
cm_mail($to, $lang, array('subject' => $subject, 'body' => $body));
```

**Comment by anotherjames** [comment]
Turns out, core's system module totally does this already :-D
