### ISSUE TITLE
This can cause a division by 0 error

### ISSUE THREAD

**Issue by darthsteven** [computerminds/cm_tools#26]
https://github.com/computerminds/cm_tools/blob/eefa60b82c77b9c651b8c81485db0e3780977e7b/includes/profile.inc#L100

If the total number of items is 0, then there's a division by 0 :(

**Comment by stevetweeddale** [comment]
This just happened on alfresco live!

**Comment by anotherjames** [comment]
I enjoyed reading this recently: https://www.hillelwayne.com/post/divide-by-zero/ ...though I admit I skipped over the maths-heavy bits...

**Comment by anotherjames** [comment]
This just happened on the staging PID too. Boooooo

**Comment by darthsteven** [comment]
Fixed in 7.x-1.1 and 7.x-2.2.
