### ISSUE TITLE
Feature request: Site monitoring page

### ISSUE THREAD

**Issue by darthsteven** [computerminds/cm_tools#32]
It would be useful to have a URL on a site that:

- Is never cached
- Does some simple checks and responds with a unique string and 200 status code
- has a stable, but unique URL

This would support adding status checks that don't get cached by Cloudfront etc.

**Comment by darthsteven** [comment]
What do you reckon?

**Comment by anotherjames** [comment]
Presumably you mean something that doesn't require you to be authenticated? Otherwise /admin/reports/status is basically this.

**Comment by darthsteven** [comment]
Yeah, non-authenticated page request.
Main consumers will be uptimerobot, pingdom or New Relic.

**Comment by darthsteven** [comment]
This got in!
